### PR TITLE
login and sing up form integrated with backend 

### PR DESCRIPTION
**Pull request by NandishM0618**
issue29
issue31
please merge it if you like it and update my points thank you.

### CODE REVIEW

**Comment by shelcia** [comment]
1. Please use this library for toast instead https://react-hot-toast.com/
2. use https://github.com/shelcia/api-docucraft/blob/main/client/src/services/models/authModel.js for API integration
like apiAuth.post(url, body).then(()).catch(())

**Comment by NandishM0618** [comment]
Okay

**Comment by shelcia** [comment]
lmk when you are done with the changes

**Comment by NandishM0618** [comment]
@shelcia for the delay as I was working on other issues right now I was busy. I will be sending a pull request today.

**Comment by NandishM0618** [comment]
I have made changes for toast but I am having issue while logging in. Can I change the code ?

**Pull request closed without merging**
