### PR TITLE
contributions.md file created

### PR DESCRIPTION
**Pull request by praptisharma28**
fixes isssue #5

@shelcia , if you are okay with this file and merging it. Merge it under iwoc24 and iwoc2024. Thanks :)

### CODE REVIEW

**Review by shelcia — APPROVED** [review]

**Comment by praptisharma28** [comment]
Hey @shelcia, thanks for merging but this PR is not counting in my dashboard of iwoc, can you please add me as an assignee to make it count?

**Comment by praptisharma28** [comment]
@shelcia , please have a look at my above comment.

**Comment by praptisharma28** [comment]
@shelcia , this PR isnt showing on my dashboard, may be bcz I was assigned to it later and you merged it before. Can you please do two things for me?
1. Open the issue again assign me, and then close it again. 
2. Please assign me on this PR too, not only the issue.

**Comment by praptisharma28** [comment]
> @shelcia , this PR isnt showing on my dashboard, may be bcz I was assigned to it later and you merged it before. Can you please do two things for me?
> 
> 1. Open the issue again assign me, and then close it again.
> 2. Please assign me on this PR too, not only the issue.


@shelcia , have a look plz

**Pull request merged**
